### ISSUE TITLE
关于“IDA with Background Knowledge”

### ISSUE THREAD

**Issue by zys07** [ZhuangyanFang/IDA-with-background-knowledge#1]
您好，我在论文“IDA with Background Knowledge”实验部分，看见您有提及“apply NIDA to the Arabidopsis thaliana data
set (Opgen-Rhein & Strimmer, 2007). ”，但是我在您的代码部分没有看见有关the Arabidopsis thaliana data
set 部分的实验内容，请问方便把这部分代码给我看看嘛？麻烦您了

**Comment by ZhuangyanFang** [comment]
您好，

我已将真实数据实验相关的代码和数据上传，具体可参考 arabidopsis-net-analysis.R 文件。

谢谢您关注我们的工作。目前整个项目还在完善中，如有进一步问题，可联系我的邮箱：fangzy_math@pku.edu.cn。

祝好！
